# Numpy

In [1]:
import numpy as np
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc("figure", figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)

In [2]:
import numpy as np

my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

In [3]:
%timeit my_arr2 = my_arr * 2
%timeit my_list2 = [x * 2 for x in my_list]

1.52 ms ± 250 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
56 ms ± 660 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


se compara los tiempos de numpy y los de python siendo numpy mas rapido


In [4]:
import numpy as np
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

## Operaciones con numpy

In [8]:
print(data)
print("array *10")
print(data * 10)
print("array sumado a si mismo")
print(data + data)

[[ 1.5 -0.1  3. ]
 [ 0.  -3.   6.5]]
array *10
[[ 15.  -1.  30.]
 [  0. -30.  65.]]
array sumado a si mismo
[[ 3.  -0.2  6. ]
 [ 0.  -6.  13. ]]


In [11]:
# dimensiones del array 2 filas 3 columnas
data.shape

(2, 3)

In [12]:
# tipo de datos almacenados en el array
data.dtype

dtype('float64')

In [14]:
#convierto una lista en un array de numpy
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [15]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
#dimensiones del array
print(arr2.ndim)
#2 filas 4 columnas
print(arr2.shape)

2
(2, 4)


In [19]:
print(arr1.dtype)# tipo de datos de array1
print(arr2.dtype)# tipos de datos de array2

float64
int64


## Zeros y Empty

In [21]:
# array de 10 ceros y una fila
print(np.zeros(10))
# array de 0 de 3 filas y 6 columnas
print(np.zeros((3, 6)))
# inicializa un array vacio distinto a zeros de 3 dimensiones
print(np.empty((2, 3, 2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [23]:
np.arange(15)#array sin for de los numeros del 0 al 14

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
arr1 = np.array([1, 2, 3], dtype=np.float64)#tipo de dato float
arr2 = np.array([1, 2, 3], dtype=np.int32)#tipo de dato int
print(arr1.dtype)
print(arr2.dtype)

float64
int32


## conversion de arrays a otros tipos de datos

In [28]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr)
float_arr.dtype

[1 2 3 4 5]
int64
[1. 2. 3. 4. 5.]


dtype('float64')

In [29]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr
#cambiado a int
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [39]:
numeric_strings = np.array(["1.25", "-9.6", "42"])
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [32]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [33]:
zeros_uint32 = np.zeros(8, dtype="u4")
zeros_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

## Operaciones entre arrays

In [35]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr)
print(arr * arr)

print(arr - arr)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [36]:
print(1 / arr)
print(arr ** 2)

[[1.     0.5    0.3333]
 [0.25   0.2    0.1667]]
[[ 1.  4.  9.]
 [16. 25. 36.]]



> operaciones booleanas

In [40]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

## Sliceing

In [41]:
arr = np.arange(10)
print(arr)
#solamente el index 5
print(arr[5])
#solamente muestra los numeros del index 5 al 8
print(arr[5:8])
#cambia los numeros del index 5 al 8 a 12
arr[5:8] = 12
#muestra el array
print(arr)

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]


In [42]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [43]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [45]:
arr_slice[:] = 64#cambia todos los elementos
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [46]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [47]:
arr2d[0][2]
arr2d[0, 2]

np.int64(3)

In [48]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [49]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [51]:

arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [52]:
arr3d[1, 0]

array([7, 8, 9])

In [54]:
x = arr3d[1]
print(x)
x[0]

[[ 7  8  9]
 [10 11 12]]


array([7, 8, 9])

In [56]:
print(arr) # muestro el array
print(arr[1:6])# agarro los indices del 1 al 6 (del 1 al 5)

[ 0  1  2  3  4 64 64 64  8  9]
[ 1  2  3  4 64]


In [58]:
print(arr2d) # muestro el array
print(arr2d[:2]) # selecciono del 0 al 2 sin tomar el 2 del array

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]


In [60]:
arr2d[:2, 1:] #seleccion como el anterior pero solamente del indice 1 al final

array([[2, 3],
       [5, 6]])

In [61]:
lower_dim_slice = arr2d[1, :2]

In [62]:
lower_dim_slice.shape

(2,)

In [63]:
arr2d[:2, 2]

array([3, 6])

In [64]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [65]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

## indices booleanos

In [66]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],
                 [-12, -4], [3, 4]])
print(names)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[  4   7]
 [  0   2]
 [ -5   6]
 [  0   0]
 [  1   2]
 [-12  -4]
 [  3   4]]


In [68]:
names == "Bob"# muestra verdadero donde el elemento sea igual a Bob

array([ True, False, False,  True, False, False, False])

In [ ]:
data[names == "Bob"]

In [ ]:
data[names == "Bob", 1:]
data[names == "Bob", 1]

In [ ]:
names != "Bob"
~(names == "Bob")
data[~(names == "Bob")]

In [ ]:
cond = names == "Bob"
data[~cond]

In [ ]:
mask = (names == "Bob") | (names == "Will")
mask
data[mask]

In [ ]:
data[data < 0] = 0
data

In [ ]:
data[names != "Joe"] = 7
data

In [ ]:
arr = np.zeros((8, 4))
for i in range(8):
    arr[i] = i
arr

In [ ]:
arr[[4, 3, 0, 6]]

In [ ]:
arr[[-3, -5, -7]]

In [ ]:
arr = np.arange(32).reshape((8, 4))
arr
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

In [ ]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

In [ ]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]
arr[[1, 5, 7, 2], [0, 3, 1, 2]] = 0
arr

In [ ]:
arr = np.arange(15).reshape((3, 5))
arr
arr.T

In [ ]:
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])
arr
np.dot(arr.T, arr)

In [ ]:
arr.T @ arr

In [ ]:
arr
arr.swapaxes(0, 1)

In [ ]:
samples = np.random.standard_normal(size=(4, 4))
samples

In [ ]:
from random import normalvariate
N = 1_000_000
%timeit samples = [normalvariate(0, 1) for _ in range(N)]
%timeit np.random.standard_normal(N)

In [ ]:
rng = np.random.default_rng(seed=12345)
data = rng.standard_normal((2, 3))

In [ ]:
type(rng)

In [ ]:
arr = np.arange(10)
arr
np.sqrt(arr)
np.exp(arr)

In [ ]:
x = rng.standard_normal(8)
y = rng.standard_normal(8)
x
y
np.maximum(x, y)

In [ ]:
arr = rng.standard_normal(7) * 5
arr
remainder, whole_part = np.modf(arr)
remainder
whole_part

In [ ]:
arr
out = np.zeros_like(arr)
np.add(arr, 1)
np.add(arr, 1, out=out)
out

In [ ]:
points = np.arange(-5, 5, 0.01) # 100 equally spaced points
xs, ys = np.meshgrid(points, points)
ys

In [ ]:
z = np.sqrt(xs ** 2 + ys ** 2)
z

In [ ]:
import matplotlib.pyplot as plt
plt.imshow(z, cmap=plt.cm.gray, extent=[-5, 5, -5, 5])
plt.colorbar()
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")

In [ ]:
plt.draw()

In [ ]:
plt.close("all")

In [ ]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [ ]:
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]
result

In [ ]:
result = np.where(cond, xarr, yarr)
result

In [ ]:
arr = rng.standard_normal((4, 4))
arr
arr > 0
np.where(arr > 0, 2, -2)

In [ ]:
np.where(arr > 0, 2, arr) # set only positive values to 2

In [ ]:
arr = rng.standard_normal((5, 4))
arr
arr.mean()
np.mean(arr)
arr.sum()

In [ ]:
arr.mean(axis=1)
arr.sum(axis=0)

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum()

In [ ]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

In [ ]:
arr.cumsum(axis=0)
arr.cumsum(axis=1)

In [ ]:
arr = rng.standard_normal(100)
(arr > 0).sum() # Number of positive values
(arr <= 0).sum() # Number of non-positive values

In [ ]:
bools = np.array([False, False, True, False])
bools.any()
bools.all()

In [ ]:
arr = rng.standard_normal(6)
arr
arr.sort()
arr

In [ ]:
arr = rng.standard_normal((5, 3))
arr

In [ ]:
arr.sort(axis=0)
arr
arr.sort(axis=1)
arr

In [ ]:
arr2 = np.array([5, -10, 7, 1, 0, -3])
sorted_arr2 = np.sort(arr2)
sorted_arr2

In [ ]:
names = np.array(["Bob", "Will", "Joe", "Bob", "Will", "Joe", "Joe"])
np.unique(names)
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

In [ ]:
sorted(set(names))

In [ ]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

In [ ]:
arr = np.arange(10)
np.save("some_array", arr)

In [ ]:
np.load("some_array.npy")

In [ ]:
np.savez("array_archive.npz", a=arr, b=arr)

In [ ]:
arch = np.load("array_archive.npz")
arch["b"]

In [ ]:
np.savez_compressed("arrays_compressed.npz", a=arr, b=arr)

In [ ]:
!rm some_array.npy
!rm array_archive.npz
!rm arrays_compressed.npz

In [ ]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x
y
x.dot(y)

In [ ]:
np.dot(x, y)

In [ ]:
x @ np.ones(3)

In [ ]:
from numpy.linalg import inv, qr
X = rng.standard_normal((5, 5))
mat = X.T @ X
inv(mat)
mat @ inv(mat)

In [ ]:
import random
position = 0
walk = [position]
nsteps = 1000
for _ in range(nsteps):
    step = 1 if random.randint(0, 1) else -1
    position += step
    walk.append(position)


In [ ]:
plt.figure()

In [ ]:
plt.plot(walk[:100])

In [ ]:
nsteps = 1000
rng = np.random.default_rng(seed=12345)  # fresh random generator
draws = rng.integers(0, 2, size=nsteps)
steps = np.where(draws == 0, 1, -1)
walk = steps.cumsum()

In [ ]:
walk.min()
walk.max()

In [ ]:
(np.abs(walk) >= 10).argmax()

In [ ]:
nwalks = 5000
nsteps = 1000
draws = rng.integers(0, 2, size=(nwalks, nsteps)) # 0 or 1
steps = np.where(draws > 0, 1, -1)
walks = steps.cumsum(axis=1)
walks

In [ ]:
walks.max()
walks.min()

In [ ]:
hits30 = (np.abs(walks) >= 30).any(axis=1)
hits30
hits30.sum() # Number that hit 30 or -30

In [ ]:
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(axis=1)
crossing_times

In [ ]:
crossing_times.mean()

In [ ]:
draws = 0.25 * rng.standard_normal((nwalks, nsteps))